import: Activiti/activiti-scripts:.travis.java.yml@develop

stages:
- name: verify
- name: tag
  if: type != pull_request
- name: deploy
  if: type != pull_request
- name: updatebot
  if: type != pull_request
jobs:
  include:
  - name: Verify build
    stage: verify
    script:
    - mvn verify -B
  - name: Create a tag
    stage: tag
    script: |
      mvn versions:set -DnewVersion=$(cat VERSION)
      git add --all
      git commit -m "Release $(cat VERSION)" --allow-empty
      git tag -fa v$(cat VERSION) -m "Release version $(cat VERSION)"
      git push -f -q https://${GITHUB_TOKEN}@github.com/Activiti/Activiti.git v$(cat VERSION)
  - name: Deploy to nexus
    stage: deploy
    script:
    - mvn versions:set -DnewVersion=$(cat VERSION)
    - mvn clean deploy -DskipTests
  - name: Update versions in other components
    stage: updatebot
    script:
    - export VERSION=$(cat VERSION)| make updatebot/push-version
env:
  global:
    secure: "XqLfCDdsDgWYlH5XLc1RaJcWwaajNFYsrl6mM4gzj7UTUdw46ymwf9BuSVWOGG3Ti46OEryaLmwD1o0fAnDjbs7zFMDsyzfprkDS2Ju2nxteN9b1dKYuE0MuyKNSYtq6o6r+8HBMDprpe0gm4bcmRXYb/zaOdNPjRI7bYY2SRYA="
